SELECT A.SNAME , B.SNAME , A.CITY FROM SALESPEOPLE A , SALESPEOPLE B
WHERE A.CITY = B.CITY AND  A.SNAME < B.SNAME;

SELECT CNAME , CITY FROM CUSTOMER WHERE RATING = ( SELECT RATING FROM CUSTOMER WHERE CNAME = 'HOFFMAN');


  