SELECT ONUM , CNAME FROM ORDERS O , CUSTOMER C  WHERE C.CNUM = O.CNUM ;

SELECT CNAME , SNAME , ONUM FROM ORDERS O , CUSTOMER C , SALESPEOPLE S WHERE O.SNUM = C.SNUM AND O.SNUM = S.SNUM;

SELECT CNAME , S.SNUM , COMM*100 "RATE" FROM CUSTOMER C , SALESPEOPLE S WHERE C.SNUM = S.SNUM AND COMM >.12;

SELECT AMT , COMM FROM CUSTOMER C , SALESPEOPLE S , ORDERS O WHERE C.SNUM = S.SNUM AND S.SNUM = O.SNUM AND RATING > 100;




