SELECT * FROM ORDERS WHERE ODATE = '1990-10-03' OR ODATE = '1990-10-04';

SELECT * FROM CUSTOMER WHERE SNAME IN
(SELECT SNUM FROM SALESPEOPLE WHERE
SNAME = 'PEEL' OR SNAME = 'MOTIKA');


SELECT *
FROM customer
WHERE cname LIKE 'a%'
  OR cname LIKE 'b%'
  OR cname LIKE 'C%'
  OR cname LIKE 'D%'
  OR cname LIKE 'E%'
  OR cname LIKE 'F%'
  OR cname LIKE 'G%' ;
  
  SELECT * FROM CUSTOMER WHERE CNAME LIKE 'C%';
  
  SELECT * FROM ORDERS WHERE AMT IS NOT NULL;
