SELECT * FROM ORDERS WHERE ODATE = '1990-10-03';
SELECT COUNT(ONUM) TOTAL_ORDER FROM ORDERS WHERE ODATE = '1990-10-03';
SELECT COUNT(CNAME) NON_NULL FROM CUSTOMER WHERE CITY IS NOT NULL ;
SELECT MIN(AMT) "MIN_AMOUNT" , CNUM
			FROM ORDERS GROUP BY CNUM;
SELECT * FROM CUSTOMER WHERE CNAME LIKE 'G%'
				order by CNAME;
SELECT MAX( RATING ) "HIGH RATE" , CITY  FROM CUSTOMER;
SELECT COUNT(ODATE)||' SALES PERSON REGI' "TOTAL",
       ODATE
FROM ORDERS
GROUP BY ODATE;

