SELECT ONUM , SNUM ,AMT, (AMT*12)/100  AS 'COMM' FROM ORDERS;


SELECT 'FOR THE CITY ' || CITY || ', THE HIGHEST RATING IS  : (' ||
MAX(RATING) || ')'
FROM CUSTOMER GROUP BY CITY;

SELECT RATING, CNAME, SNUM
FROM CUSTOMER
ORDER BY RATING DESC;

SELECT COUNT(ODATE) AS 'TOTAL ORDERS' , ODATE FROM ORDERS GROUP BY ODATE ORDER BY 'TOTAL ORDERS' ;

