SELECT ONUM, AMT ,ODATE FROM ORDERS;
SELECT * FROM CUSTOMER WHERE SNUM = 1001;

SELECT CITY , SNAME , SNUM ,COMM FROM SALESPEOPLE;

SELECT * FROM CUSTOMER;

SELECT rating||' '||cname "employee rating"
FROM customer
WHERE city='sanjose';

SELECT DISTINCT SNUM FROM salespeople;


